StoreApp/Models/StaffViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StoreApp.Models
{
    public class StaffViewModel
    {
        
        [Required(ErrorMessage = "First Name Cannot be Null")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        public string LastName { get; set; }
        
        [Required(ErrorMessage = "Email Cannot be Null")]
        [EmailAddress]
        public string Email { get; set; }

        public string PhoneNumber { get; set; }
    }
}

StoreApp/Controllers/StaffController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StoreApp.Service;
using static System.Web.HttpContext;

namespace StoreApp.Controllers
{
    [Authorize(Roles = "STAFF")]
    public class StaffController : Controller
    {
        private ApplicationUserManager _manager;
        private IStaffService _staffService;

        public StaffController(){}

        public StaffController(ApplicationUserManager userManager, IStaffService staffService)
        {
            _manager = userManager;
            _staffService = staffService;
        }

        // public ApplicationUserManager UserManager
        // {
        //     get { return _manager ?? Current.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
        //     set { _manager = value; }
        // }
        //
        // public IStaffService StaffService
        // {
        //     get
        //     {
        //         return _staffService ?? new StaffServiceImpl();
        //     }
        //     set
        //     {
        //         _staffService = value;
        //     }
        // }

        // GET
        public ActionResult HomePage()
        {
            return View();
        }

        //view Audit trails
        public ActionResult CheckAuditLogs()
        {
            var userId = Current.User.Identity.GetUserId();
            return View(_staffService.GetAllAuditTrails(userId));
        }

        //view Invoices 
        public ActionResult CheckAllInvoices()
        {
            var userId = Current.User.Identity.GetUserId();
            return View(_staffService.GetAllInvoices(userId));
        }

        //View Orders
        public ActionResult CheckOrders()
        {
            var userId = Current.User.Identity.GetUserId();
            return View(_staffService.GetAllOrders(userId));
        }

        public ActionResult CheckAllCustomers()
        {
            var userId = Current.User.Identity.GetUserId();
            return View(_staffService.GetAllCustomers(userId));
        }
    }
}

StoreApp/Views/Staff/CheckAllCustomers.cshtml
@model IEnumerable<StoreApp.Domains.Customer>

@{
    ViewBag.Title = "CheckAllCustomers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckAllCustomers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
    </tr>
}

</table>

StoreApp/Views/Staff/CheckAllInvoices.cshtml
@model IEnumerable<StoreApp.Domains.Invoice>

@{
    ViewBag.Title = "CheckAllInvoices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckAllInvoices</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
    </tr>
}

</table>

StoreApp/Views/Staff/CheckAuditLogs.cshtml
@model IEnumerable<StoreApp.Domains.AuditTrail>

@{
    ViewBag.Title = "CheckAuditLogs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckAuditLogs</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActionDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeOfAction)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActionDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeOfAction)
        </td>
    </tr>
}

</table>

StoreApp/Views/Staff/CheckOrders.cshtml
@model IEnumerable<StoreApp.Domains.Order>

@{
    ViewBag.Title = "CheckOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckOrders</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
    </tr>
}

</table>

StoreApp/Views/Staff/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HomePage</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="center-block">
                    <i class="glyphicon glyphicon-dashboard" style="size: 50px"></i>
                    <p>@Html.ActionLink("Check Audit Logs", "CheckAuditLogs", "Staff")</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="center-block">
                    <i class="glyphicon glyphicon-inbox" style="size: 50px"></i>
                    <p>@Html.ActionLink("Check Invoices", "CheckAllInvoices", "Staff")</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="center-block">
                    <i class="glyphicon glyphicon-barcode" style="size: 50px"></i>
                    <p>@Html.ActionLink("Check Orders", "CheckOrders", "Staff")</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="center-block">
                    <i class="glyphicon glyphicon-user" style="size: 50px"></i>
                    <p>@Html.ActionLink("Check Users List", "", "")</p>
                </div>
            </div>
        </div>
    </div>
</div>