StoreApp/Models/SupplierViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StoreApp.Models
{
    public class SupplierViewModel
    {
        [Required(ErrorMessage = "First Name Cannot be Null")]
        [Display(Name = "Supplier Name")]
        public string SupplierName { get; set; }
        
        [Required(ErrorMessage = "Email Cannot be Null")]
        [EmailAddress]
        public string Email { get; set; }

        public string PhoneNumber { get; set; }
        
        [Required(ErrorMessage = "Password not Valid")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password cannot be null")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password Mismatch")]
        public string ConfirmPassword { get; set; }
    }
}

StoreApp/Models/UploadItemViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace StoreApp.Models
{
    public class UploadItemViewModel
    {
        [Required(ErrorMessage = "Item Name Cannot be Null")]
        [Display(Name = "Item Name")]
        public string ItemName { get; set; }
        
        [Required(ErrorMessage = "Item Price Cannot be Null")]
        [Display(Name = "Item Price")]
        public decimal ItemPrice { get; set; }
        
        [Required(ErrorMessage = "Item Quantity Cannot be Null")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Required]
        [Display(Name = "Item Image")]
        public HttpPostedFileBase File { get; set; }

        [Required(ErrorMessage = "Expiry Date Cannot be Null")]
        [Display(Name = "Expiry Date")]
        public DateTime ExpiryDate { get; set; }
        
        [Required(ErrorMessage = "Category Cannot be Null")]
        [Display(Name = "Category")]
        public string Category { get; set; }
    }
}

StoreApp/Controllers/SupplierController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using StoreApp.Models;
using static System.Web.HttpContext;
using StoreApp.Service;
using StoreApp.Service.ServiceImpl;

namespace StoreApp.Controllers
{
    [Authorize(Roles = "SUPPLIER")]
    public class SupplierController : Controller
    {
     
        private ApplicationUserManager _manager;
        private ApplicationSignInManager _signInManager;
        private IUserService _userService;
        private ISupplierService _supplierService;
        private IAuditTrailService _auditTrailService;
        
        public SupplierController(){}

        public SupplierController(ApplicationUserManager userManager, ApplicationSignInManager signInManager, IUserService userService, IAuditTrailService auditTrailService, ISupplierService supplierService)
        {
            _manager = userManager;
            _signInManager = signInManager;
            _userService = userService;
            _auditTrailService = auditTrailService;
            _supplierService = supplierService;
        }

        // public ApplicationSignInManager SignInManager
        // {
        //     get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
        //     private set { __signInManager = value; }
        // }
        //
        // public ApplicationUserManager UserManager
        // {
        //     get
        //     {
        //         return _manager ?? Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
        //     }
        //     set
        //     {
        //         _manager = value;
        //     }
        // }
        //
        // public ISupplierService SupplierService
        // {
        //     get
        //     {
        //         return _supplierService ?? new SupplierServiceImpl();
        //     }
        //     set
        //     {
        //         _supplierService = value;
        //     }
        // }
        //
        // public IUserService UserService
        // {
        //     get
        //     {
        //         return _userService ?? new UserServiceImpl();
        //     }
        //     set
        //     {
        //         _userService = value;
        //     }
        // }
        //
        // public IAuditTrailService AuditTrailService
        // {
        //     get
        //     {
        //         return _auditTrailService ?? new AuditTrailServiceImpl();
        //     }
        //     set
        //     {
        //         _auditTrailService = value;
        //     }
        // }
        // GET

        public ActionResult UploadItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadItem(UploadItemViewModel model)
        {

            try
            {
                var userId = Current.User.Identity.GetUserId();
                _supplierService.UploadItem(model,userId);
                return View("HomePage", _supplierService.GetAllSupplierItems(userId));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ViewBag.Error = e.Message;
                View("Error");
            }

            return View();
        }

        public ActionResult HomePage()
        {
            try
            {
                var userId = Current.User.Identity.GetUserId();
                return View(_supplierService.GetAllSupplierItems(userId));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ViewBag.Error = e.Message;
                View("Error");
            }

            return View();
        }
        
        [AllowAnonymous]
        public ActionResult CreateSupplier()
        {
            return View();
        }
        
        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> CreateSupplier(SupplierViewModel model)
        {

            var resultSet = await _userService.CreateUser(null, null, model);
            if (resultSet.Item1 != null)
            {
                
                if (resultSet.Item2)
                {
                    await _signInManager.SignInAsync(resultSet.Item1, false, false);
                    _auditTrailService.CreateAuditTrail(resultSet.Item1.Id, "User Logged In");
                    return View("HomePage", _supplierService.GetAllSupplierItems(resultSet.Item1.Id));
                }
            }else if (resultSet.Item1 == null && resultSet.Item3 != null)
            {
                ViewBag.HasError = true;
                ViewBag.Error = resultSet.Item3;
            }
            return View();
        }
    }
}

StoreApp/Views/Supplier/CreateSupplier.cshtml
@model StoreApp.Models.SupplierViewModel

@{
    ViewBag.Title = "CreateSupplier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateSupplier</h2>
@if (ViewBag.HasError == true)
{
    foreach (var error in ViewBag.Error)
    {
        <h1>@error</h1>
    }
    
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SupplierViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SupplierName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SupplierName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreApp/Views/Supplier/HomePage.cshtml
@model IEnumerable<StoreApp.Domains.Item>

@{
    ViewBag.Title = "HomePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome Supplier</h2>

<p> @Html.ActionLink("Upload New Item", "UploadItem")</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiryDate)
        </td>
        @* <td> *@
        @*     <button> *@
        @*         @Html.ActionLink("Supply More", "") *@
        @*     </button> *@
        @* </td> *@
    </tr>
}

</table>

StoreApp/Views/Supplier/UploadItem.cshtml
@model StoreApp.Models.UploadItemViewModel

@{
    ViewBag.Title = "UploadItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UploadItem</h2>


@using (Html.BeginForm("UploadItem", "Supplier", FormMethod.Post,new {enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UploadItemViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.File, new { type = "file"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}